name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        working-directory: ./'Customer Service'
        run: |
          ls ${{ github.workspace }}
