name: GitHub Actions Demo
on: [push]
defaults:
      run:
        working-directory: /home/runner/work/Microservice-eCommerce/Microservice-eCommerce/Customer Service/
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
  Dockerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag customer-service-image:v1.0.1
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: it19143200
          password: 0775574685Ds
    
